export const initialCardData = {
  'HTML': {
    name: 'HTML',
    type: 'Foundation',
    description: 'O mestre da estrutura, capaz de erguer a base de qualquer mundo digital. Sua essência reside na organização e na capacidade de dar forma ao conteúdo.',
    stats: { PWR: 60, VEL: 85, FLX: 90, COM: 95, CRV: 80 },
    color: '#f97316', // Main color for card border and footer bg
    gradient: 'linear-gradient(to right, #f97316, #fb923c)', // Header background gradient
    cardHeaderBorderColor: '#ea580c', // Header bottom border color
    typeBgColor: '#fcd34d', // Type background color
    typeTextColor: '#8b5f00', // Type text color
    statsBgColor: '#ffedd5', // Stats background color
    statsBorderColor: '#fed7aa', // Stats top border color and description top border
    statsLabelColor: '#334155', // Stats label text color (general as per original HTML)
    statsValueColor: '#c2410c', // Stats value text color
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a skilled craftsman or architect animal (e.g., a beaver or badger) diligently constructing a digital landscape or a magnificent web page structure. The creature should be surrounded by floating, glowing HTML elements like <div>, <p>, <img>, emphasizing its role in building foundational web structures. The background should evoke a sense of an organized, foundational digital world, possibly with a blueprint overlay or a grid. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom, and no parts are cut off at the edges. The overall aesthetic should be industrious, organized, and suitable for a fantasy card game, with warm, inviting colors and a sense of creation. High detail, sharp lines, epic feel."
  },
  'Python': {
    name: 'Python',
    type: 'Data Type',
    description: 'Uma criatura mística e versátil, capaz de manipular dados e automatizar tarefas com sua inteligência ágil. Seus movimentos são fluidos e seu poder, ilimitado.',
    stats: { PWR: 85, VEL: 75, FLX: 95, COM: 90, CRV: 90 },
    color: '#38bdf8',
    gradient: 'linear-gradient(to right, #38bdf8, #60a5fa)',
    cardHeaderBorderColor: '#1e7bcf',
    typeBgColor: '#93c5fd',
    typeTextColor: '#0c4a6e',
    statsBgColor: '#e0f2fe',
    statsBorderColor: '#93c5fd',
    statsLabelColor: '#334155',
    statsValueColor: '#0369a1',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a majestic, mystical serpent representing Python. The serpent should have scales that subtly reflect the blue and yellow colors of the Python logo, and perhaps abstract patterns hinting at code or data structures. It should be in a dynamic, slightly coiled or vertically oriented pose, designed to fill a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom. Its eyes should glow with intelligence. The overall aesthetic should be powerful, magical, and suitable for a fantasy card game, with vibrant colors and a sense of awe. The main subject (the serpent) should be clearly visible and well-framed within the image, ensuring it fills the frame without significant empty space at the top or bottom, and no parts are cut off at the edges. High detail, sharp lines, epic feel."
  },
  'Java': {
    name: 'Java',
    type: 'Enterprise',
    description: 'Um guardião robusto e confiável, forjado para construir mundos complexos e garantir a estabilidade. Sua força reside em sua portabilidade e resiliência inabalável.',
    stats: { PWR: 75, VEL: 60, FLX: 70, COM: 95, CRV: 70 },
    color: '#ef4444',
    gradient: 'linear-gradient(to right, #ef4444, #f87171)',
    cardHeaderBorderColor: '#be123c',
    typeBgColor: '#fca5a5',
    typeTextColor: '#7f1d1d',
    statsBgColor: '#fee2e2',
    statsBorderColor: '#fca5a5',
    statsLabelColor: '#334155',
    statsValueColor: '#991b1b',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a robust and powerful bear representing Java. The bear should have subtle patterns or markings that evoke circuit boards or code blocks, and perhaps a glowing coffee cup symbol on its chest or integrated into its design, symbolizing 'Write Once, Run Anywhere' and its enterprise strength. It should have an aura of stability and reliability. The background should be a bustling digital city of servers or a serene, robust digital forest, emphasizing its wide deployment and enduring power. The main subject (the bear) should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom. The overall aesthetic should be strong, reliable, and suitable for a fantasy card game, with bold colors like red, dark gray, and subtle orange accents. High detail, sharp lines, epic feel."
  },
  'Dart': {
    name: 'Dart',
    type: 'Cross-Platform',
    description: 'Um espírito ágil e versátil, capaz de criar interfaces deslumbrantes em múltiplas plataformas com velocidade e eficiência incomparáveis.',
    stats: { PWR: 80, VEL: 90, FLX: 85, COM: 75, CRV: 85 },
    color: '#06b6d4',
    gradient: 'linear-gradient(to right, #06b6d4, #22d3ee)',
    cardHeaderBorderColor: '#0e7490',
    typeBgColor: '#99f6e4',
    typeTextColor: '#0e7490',
    statsBgColor: '#e0f7fa',
    statsBorderColor: '#99f6e4',
    statsLabelColor: '#334155',
    statsValueColor: '#0f766e',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a swift, agile, and elegant bird (e.g., a hummingbird or a falcon) representing Dart. The creature should have subtle glowing lines or patterns on its feathers that evoke Flutter's butterfly logo or modern UI components. It should be in a fluid, energetic pose, suggesting rapid development and smooth animations. The background should be a clean, modern digital landscape, possibly with subtle code lines or mobile device outlines. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom. The overall aesthetic should be dynamic, efficient, and suitable for a fantasy card game, with vibrant blues and purples. High detail, sharp lines, epic feel."
  },
  'CSS': {
    name: 'CSS',
    type: 'Visual',
    description: 'A mestra da estética, capaz de transformar a estrutura bruta em uma obra de arte visual. Seus poderes controlam cores, layouts e a beleza de cada pixel.',
    stats: { PWR: 70, VEL: 85, FLX: 95, COM: 95, CRV: 80 },
    color: '#6366f1',
    gradient: 'linear-gradient(to right, #6366f1, #818cf8)',
    cardHeaderBorderColor: '#4338ca',
    typeBgColor: '#c7d2fe',
    typeTextColor: '#4338ca',
    statsBgColor: '#eef2ff',
    statsBorderColor: '#c7d2fe',
    statsLabelColor: '#334155',
    statsValueColor: '#4f46e5',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a graceful and artistic chameleon or peacock representing CSS. The creature's skin or feathers should subtly shift colors and patterns, symbolizing dynamic styling and visual transformations. It could be interacting with abstract representations of cascading style sheets or glowing design elements. The background should be a vibrant, evolving visual landscape, showing elements transforming from basic shapes to beautifully styled interfaces. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom, and no parts are cut off at the edges. The overall aesthetic should be elegant, artistic, and suitable for a fantasy card game, with rich, harmonious colors and a sense of visual magic. High detail, sharp lines, epic feel."
  },
  'Tailwind CSS': {
    name: 'Tailwind CSS',
    type: 'Framework',
    description: 'O arquiteto da velocidade, que constrói interfaces modernas com blocos de utilidade. Sua essência reside na agilidade do desenvolvimento e na modularidade sem precedentes.',
    stats: { PWR: 75, VEL: 95, FLX: 90, COM: 85, CRV: 70 },
    color: '#06b6d4',
    gradient: 'linear-gradient(to right, #06b6d4, #22d3ee)',
    cardHeaderBorderColor: '#0e7490',
    typeBgColor: '#a5f3fc',
    typeTextColor: '#0e7490',
    statsBgColor: '#e0faff',
    statsBorderColor: '#a5f3fc',
    statsLabelColor: '#334155',
    statsValueColor: '#0891b2',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a nimble and efficient construction animal (e.g., a beaver or a ant) representing Tailwind CSS. The creature should be rapidly assembling glowing, abstract utility blocks or UI components, emphasizing speed and modularity. The background should be a clean, modern design grid or a blueprint, hinting at its utility-first approach. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it fills the frame without significant empty space at the top or bottom, and no parts are cut off at the edges. The overall aesthetic should be sleek, efficient, and suitable for a fantasy card game, with a focus on blues, purples, and grays. High detail, sharp lines, epic feel."
  },
  'Rust': {
    name: 'Rust',
    type: 'Systems',
    description: 'O construtor de sistemas, forjado para performance e segurança sem precedentes. Sua força reside na memória segura e na concorrência sem data races.',
    stats: { PWR: 95, VEL: 90, FLX: 60, COM: 75, CRV: 40 },
    color: '#dea584',
    gradient: 'linear-gradient(to right, #dea584, #ff7f50)',
    cardHeaderBorderColor: '#a0522d',
    typeBgColor: '#cc845c',
    typeTextColor: '#a0522d',
    statsBgColor: '#f2e0d4',
    statsBorderColor: '#cc845c',
    statsLabelColor: '#334155',
    statsValueColor: '#8b4513',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a powerful and precise wolf or dragon representing Rust. The creature should have subtle metallic or circuit-like patterns, symbolizing its close relation to hardware and high performance. It should exude an aura of raw power, control, and efficiency. The background should be a dynamic, complex digital landscape with glowing lines of code or intricate gears, emphasizing its use in systems programming and game development. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be strong, technical, and suitable for a fantasy card game, with a focus on dark blues, grays, and electric accents. High detail, sharp lines, epic feel."
  },
  'Golang': {
    name: 'Golang',
    type: 'Concurrency',
    description: 'O mestre da concorrência, construído para eficiência e escalabilidade. Sua força reside na simplicidade, na compilação rápida e na capacidade de lidar com múltiplas tarefas simultaneamente.',
    stats: { PWR: 90, VEL: 95, FLX: 70, COM: 80, CRV: 85 },
    color: '#00ADD8',
    gradient: 'linear-gradient(to right, #00ADD8, #66D9EF)',
    cardHeaderBorderColor: '#007996',
    typeBgColor: '#B3E5FC',
    typeTextColor: '#007996',
    statsBgColor: '#E0F7FA',
    statsBorderColor: '#B3E5FC',
    statsLabelColor: '#334155',
    statsValueColor: '#005F7F',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a nimble and friendly Gopher mascot representing Golang. The Gopher should be surrounded by glowing, interconnected channels and goroutines flowing smoothly, symbolizing its efficiency and concurrency. It should be in a dynamic pose, suggesting rapid processing and efficient task management. The background should be a clean, minimalist digital landscape, hinting at its simplicity and performance. The main subject (the Gopher) should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be clean, efficient, and suitable for a fantasy card game, with a focus on blues, grays, and subtle orange accents. High detail, sharp lines, epic feel."
  },
  'Actix': {
    name: 'Actix',
    type: 'Web Framework',
    description: 'Um framework web de alta performance, construído em Rust, conhecido por sua velocidade assíncrona e segurança robusta, ideal para aplicações escaláveis.',
    stats: { PWR: 95, VEL: 90, FLX: 65, COM: 70, CRV: 45 },
    color: '#6a0dad',
    gradient: 'linear-gradient(to right, #6a0dad, #9932cc)',
    cardHeaderBorderColor: '#4b0082',
    typeBgColor: '#d8bfd8',
    typeTextColor: '#4b0082',
    statsBgColor: '#e6e6fa',
    statsBorderColor: '#d8bfd8',
    statsLabelColor: '#334155',
    statsValueColor: '#8a2be2',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a swift and powerful animal (e.g., a cheetah or a lightning bird) representing Actix. The creature should have subtle glowing energy lines or patterns, symbolizing its high performance and asynchronous nature. It should be in a dynamic, action-oriented pose, suggesting rapid processing and efficient data transfer. The background should be a dynamic, futuristic cityscape or a digital realm with streaks of light, hinting at high-speed data flow. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be sleek, powerful, and suitable for a fantasy card game, with a focus on deep blues, purples, and electric accents. High detail, sharp lines, epic feel."
  },
  'GCP': {
    name: 'GCP',
    type: 'Cloud Platform',
    description: 'O titã da nuvem, capaz de escalar infraestruturas e impulsionar inovações com inteligência artificial. Sua força reside na rede global e nos serviços sem limites.',
    stats: { PWR: 95, VEL: 90, FLX: 98, COM: 80, CRV: 65 },
    color: '#4285F4',
    gradient: 'linear-gradient(to right, #4285F4, #66A3FF)',
    cardHeaderBorderColor: '#1A73E8',
    typeBgColor: '#C5E1FF',
    typeTextColor: '#1A73E8',
    statsBgColor: '#E8F0FE',
    statsBorderColor: '#C5E1FF',
    statsLabelColor: '#334155',
    statsValueColor: '#1967D2',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a majestic and expansive creature (e.g., a celestial dragon or a giant eagle) representing Google Cloud Platform (GCP). The creature should be depicted soaring above a stylized globe or a network of interconnected servers, with glowing data streams or abstract cloud shapes around it. It should exude an aura of global reach, scalability, and intelligence. The background should be a vast, interconnected digital sky with subtle representations of cloud regions and data centers. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be grand, futuristic, and suitable for a fantasy card game, with a focus on blues, whites, and subtle rainbow accents (Google colors). High detail, sharp lines, epic feel."
  },
  'AWS': {
    name: 'AWS',
    type: 'Cloud Platform',
    description: 'O pioneiro da nuvem, oferecendo uma vasta gama de serviços para construir e escalar qualquer aplicação. Sua força reside na abrangência, confiabilidade e inovação contínua.',
    stats: { PWR: 98, VEL: 90, FLX: 95, COM: 99, CRV: 60 },
    color: '#FF9900',
    gradient: 'linear-gradient(to right, #FF9900, #FFB347)',
    cardHeaderBorderColor: '#E67E22',
    typeBgColor: '#FFD799',
    typeTextColor: '#E67E22',
    statsBgColor: '#FFF8E1',
    statsBorderColor: '#FFD799',
    statsLabelColor: '#334155',
    statsValueColor: '#D35400',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a powerful and vast creature (e.g., a colossal elephant or a mythical griffin) representing Amazon Web Services (AWS). The creature should be depicted as a 'Cloud Sovereign' or 'Infrastructure Weaver', standing atop a stylized globe or a massive, interconnected network of servers, with glowing data streams or abstract service icons around it. It should exude an aura of immense power, reliability, and global presence. The background should be a dynamic, expansive digital sky with subtle representations of global regions and data centers. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be grand, reliable, and suitable for a fantasy card game, with a focus on blues, whites, and the iconic AWS orange. High detail, sharp lines, epic feel."
  },
  'Kafka': {
    name: 'Kafka',
    type: 'Messaging',
    description: 'O mensageiro distribuído, construído para lidar com fluxos de dados em tempo real em larga escala. Sua força reside na alta vazão, tolerância a falhas e escalabilidade.',
    stats: { PWR: 90, VEL: 95, FLX: 80, COM: 90, CRV: 60 },
    color: '#231F20',
    gradient: 'linear-gradient(to right, #231F20, #4D4D4D)',
    cardHeaderBorderColor: '#333333',
    typeBgColor: '#E0E0E0',
    typeTextColor: '#333333',
    statsBgColor: '#F5F5F5',
    statsBorderColor: '#E0E0E0',
    statsLabelColor: '#334155',
    statsValueColor: '#555555',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a swift and robust creature (e.g., a data-carrying beetle or a multi-legged messenger insect) representing Apache Kafka. The creature should be depicted as a 'Data Stream Weaver' or 'Message Broker', efficiently moving glowing data packets or log segments through intricate digital channels. It should exude an aura of high-throughput and reliability. The background should be a dynamic, interconnected network of servers or a futuristic city with glowing data highways, emphasizing scalability and real-time processing. The main subject should be clearly visible and well-framed within a **slightly vertical rectangular aspect ratio, close to 1:1 or 4:5**, ensuring it. The overall aesthetic should be dynamic, efficient, and suitable for a fantasy card game, with a focus on dark grays, oranges, and subtle blue accents. High detail, sharp lines, epic feel."
  },
  'RabbitMQ': {
    name: 'RabbitMQ',
    type: 'Message Broker',
    description: 'O ágil mensageiro, facilitando a comunicação assíncrona entre sistemas. Sua força reside na entrega confiável, roteamento flexível e escalabilidade para filas de mensagens.',
    stats: { PWR: 85, VEL: 80, FLX: 90, COM: 90, CRV: 70 },
    color: '#FF6600',
    gradient: 'linear-gradient(to right, #FF6600, #FF9933)',
    cardHeaderBorderColor: '#E65C00',
    typeBgColor: '#FFD7B3',
    typeTextColor: '#E65C00',
    statsBgColor: '#FFF3E0',
    statsBorderColor: '#FFD7B3',
    statsLabelColor: '#334155',
    statsValueColor: '#BF4D00',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a swift and efficient rabbit representing RabbitMQ. The rabbit should be depicted as a 'Message Courier' or 'Queue Master', deftly managing glowing message packets flowing through intricate digital channels or queues. It. The overall aesthetic should be dynamic, reliable, and suitable for a fantasy card game, with a focus on oranges, grays, and subtle green accents. High detail, sharp lines, epic feel."
  },
  'Django': {
    name: 'Django',
    type: 'Web Framework',
    description: 'O framework web para perfeccionistas com prazos. Sua força reside na rapidez de desenvolvimento, segurança robusta e na vasta coleção de bibliotecas.',
    stats: { PWR: 85, VEL: 90, FLX: 70, COM: 95, CRV: 60 },
    color: '#092E20',
    gradient: 'linear-gradient(to right, #092E20, #1D6F42)',
    cardHeaderBorderColor: '#2E8B57',
    typeBgColor: '#C8E6C9',
    typeTextColor: '#2E8B57',
    statsBgColor: '#D4EDDA',
    statsBorderColor: '#C8E6C9',
    statsLabelColor: '#334155',
    statsValueColor: '#1E633F',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a charismatic jazz musician animal (e.g., a fox or a cat) playing a guitar, inspired by Django Reinhardt, representing the Django web framework. The creature should be in a dynamic pose, perhaps playing a guitar with glowing strings that emanate musical notes and subtle code patterns. The background should evoke a lively jazz club or a stage filled with digital light effects, blending the world of music and programming. It. The overall aesthetic should be energetic, sophisticated, and suitable for a fantasy card game, with a focus on warm, inviting colors and a sense of rhythm and flow. High detail, sharp lines, epic feel."
  },
  'PostgreSQL': {
    name: 'PostgreSQL',
    type: 'Database',
    description: 'O guardião robusto dos dados, conhecido por sua confiabilidade, integridade e conformidade com padrões. Sua força reside na extensibilidade e no processamento transacional avançado.',
    stats: { PWR: 95, VEL: 80, FLX: 90, COM: 90, CRV: 60 },
    color: '#336791',
    gradient: 'linear-gradient(to right, #336791, #4E83B4)',
    cardHeaderBorderColor: '#2D5E89',
    typeBgColor: '#B3D9FF',
    typeTextColor: '#2D5E89',
    statsBgColor: '#E0F2FF',
    statsBorderColor: '#B3D9FF',
    statsLabelColor: '#334155',
    statsValueColor: '#1F4560',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a majestic and robust elephant representing PostgreSQL. The elephant should be stylized, perhaps with subtle patterns on its skin resembling database tables or data structures. It should have an aura of wisdom, reliability, and strength, symbolizing data integrity and advanced features. The background should be a serene but powerful digital landscape, possibly with glowing data streams flowing into a central, secure vault-like structure, emphasizing data storage and management. It. The overall aesthetic should be grand, trustworthy, and suitable for a fantasy card game, with a focus on blues, grays, and subtle green accents. High detail, sharp lines, epic feel."
  },
  'MySQL': {
    name: 'MySQL',
    type: 'Database',
    description: 'O banco de dados relacional de código aberto, amplamente utilizado por sua velocidade e facilidade de uso. Sua força reside na performance, escalabilidade e na vasta comunidade.',
    stats: { PWR: 80, VEL: 90, FLX: 85, COM: 95, CRV: 75 },
    color: '#00758F',
    gradient: 'linear-gradient(to right, #00758F, #00A2C0)',
    cardHeaderBorderColor: '#004D60',
    typeBgColor: '#B3D9FF',
    typeTextColor: '#004D60',
    statsBgColor: '#E0F2FF',
    statsBorderColor: '#B3D9FF',
    statsLabelColor: '#334155',
    statsValueColor: '#003340',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a sleek, intelligent dolphin representing MySQL. The dolphin should be in a dynamic, powerful pose, perhaps leaping from a stylized ocean of data or interacting with glowing SQL query bubbles. Its design should subtly incorporate elements of the MySQL logo's blue and orange colors. The background should be a vibrant, interconnected digital ocean or a serene but active data realm, ensuring it. The overall aesthetic should be energetic, trustworthy, and suitable for a fantasy card game, with a focus on blues, whites, and subtle orange accents. High detail, sharp lines, epic feel."
  },
  'MongoDB': {
    name: 'MongoDB',
    type: 'NoSQL Database',
    description: 'O banco de dados NoSQL flexível, projetado para dados não estruturados e escalabilidade horizontal. Sua força reside na agilidade, na modelagem de documentos e na alta disponibilidade.',
    stats: { PWR: 90, VEL: 95, FLX: 98, COM: 90, CRV: 85 },
    color: '#47A248',
    gradient: 'linear-gradient(to right, #47A248, #6EC66E)',
    cardHeaderBorderColor: '#2E8B57',
    typeBgColor: '#C8E6C9',
    typeTextColor: '#2E8B57',
    statsBgColor: '#D4EDDA',
    statsBorderColor: '#C8E6C9',
    statsLabelColor: '#334155',
    statsValueColor: '#1E633F',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a plant-like creature representing MongoDB. The creature should be a stylized, friendly, and robust tree-like or large leaf creature, subtly incorporating the MongoDB leaf logo into its design (e.g., as part of its foliage or body pattern). It should have an aura of adaptability and growth, symbolizing its flexible data model and scalability. The background should be a vibrant, naturalistic digital garden or a forest of data nodes, emphasizing organic data growth and unstructured storage. It. The overall aesthetic should be charming, adaptable, and suitable for a fantasy card game, with bright greens, earthy tones, and subtle glowing accents. High detail, sharp lines, epic feel."
  },
  'Docker': {
    name: 'Docker',
    type: 'Containerization',
    description: 'O mestre da containerização, empacotando aplicações e suas dependências para portabilidade e execução consistente. Sua força reside na agilidade, isolamento e escalabilidade de microserviços.',
    stats: { PWR: 90, VEL: 85, FLX: 95, COM: 95, CRV: 70 },
    color: '#2496ED',
    gradient: 'linear-gradient(to right, #2496ED, #61DAFB)',
    cardHeaderBorderColor: '#1A7ACC',
    typeBgColor: '#B3E0FF',
    typeTextColor: '#1A7ACC',
    statsBgColor: '#E0F2FF',
    statsBorderColor: '#B3E0FF',
    statsLabelColor: '#334155',
    statsValueColor: '#005F99',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a majestic whale representing Docker. The whale should be stylized and powerful, with subtle elements hinting at containerization and portability, like glowing rectangular patterns on its skin or small, abstract container shapes floating around it. It. The overall aesthetic should be strong, efficient, and suitable for a fantasy card game, with a focus on blues, whites, and subtle dark accents. High detail, sharp lines, epic feel."
  },
  'Kubernetes': {
    name: 'Kubernetes',
    type: 'Orchestration',
    description: 'O mestre da orquestração, controlando e escalando contêineres com precisão. Sua força reside na automação, resiliência e gerenciamento de cargas de trabalho complexas.',
    stats: { PWR: 98, VEL: 85, FLX: 90, COM: 95, CRV: 50 },
    color: '#326CE5',
    gradient: 'linear-gradient(to right, #326CE5, #4285F4)',
    cardHeaderBorderColor: '#1A5CCF',
    typeBgColor: '#C5D9FF',
    typeTextColor: '#1A5CCF',
    statsBgColor: '#E8F0FE',
    statsBorderColor: '#C5D9FF',
    statsLabelColor: '#334155',
    statsValueColor: '#194AB8',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a powerful, multi-limbed or multi-tentacled mythical creature representing Kubernetes. This creature should be orchestrating and managing many smaller, glowing container-like entities or pods, guiding them through a complex, interconnected digital landscape. The creature's design should subtly incorporate elements of the Kubernetes logo (like the ship's wheel or geometric shapes). It should have an aura of control and intelligence. It. The overall aesthetic should be grand, complex, and suitable for a fantasy card game, with a focus on blues, purples, and glowing accents. High detail, sharp lines, epic feel."
  },
  'REST': {
    name: 'REST',
    type: 'Architectural Style',
    description: 'O estilo arquitetural fundamental para a construção de serviços web escaláveis e flexíveis. Sua força reside na simplicidade, na comunicação sem estado e na padronização de interfaces.',
    stats: { PWR: 90, VEL: 85, FLX: 98, COM: 99, CRV: 70 },
    color: '#364F6B',
    gradient: 'linear-gradient(to right, #364F6B, #5C7B9E)',
    cardHeaderBorderColor: '#2C3E50',
    typeBgColor: '#AAB8C2',
    typeTextColor: '#2C3E50',
    statsBgColor: '#F0F4F8',
    statsBorderColor: '#AAB8C2',
    statsLabelColor: '#334155',
    prompt: "a cartoony anime style illustration, 1st generation Pokemon style, featuring a sleek, intelligent dolphin representing MySQL. The dolphin should be in a dynamic, powerful pose, perhaps leaping from a stylized ocean of data or interacting with glowing SQL query bubbles. Its design should subtly incorporate elements of the MySQL logo's blue and orange colors. The background should be a vibrant, interconnected digital ocean or a serene but active data realm, ensuring it. The overall aesthetic should be energetic, trustworthy, and suitable for a fantasy card game, with a focus on blues, whites, and subtle orange accents. High detail, sharp lines, epic feel."
  },